# Generated by Django 4.0.3 on 2022-03-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTarjeta', models.CharField(max_length=50)),
                ('FechaVencimiento', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuerpoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaModificacion', models.DateTimeField(auto_now=True)),
                ('Contenido', models.TextField(blank=True)),
                ('ContenidoReverso', models.TextField(blank=True)),
                ('Tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarjeta')),
            ],
        ),
    ]
