# Generated by Django 4.0.3 on 2022-03-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarjeta_fechavencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuerpotarjeta',
            old_name='Contenido',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='cuerpotarjeta',
            old_name='ContenidoReverso',
            new_name='contenido_reverso',
        ),
        migrations.RenameField(
            model_name='cuerpotarjeta',
            old_name='FechaModificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='cuerpotarjeta',
            old_name='Tarjeta',
            new_name='tarjeta',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='FechaVencimiento',
            new_name='fecha_vencimiento',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='NombreTarjeta',
            new_name='nombre_tarjeta',
        ),
    ]
