# Generated by Django 4.0.3 on 2022-04-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tarjeta_collaborators_tarjeta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='collaborators',
            new_name='colaboradores',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='contenido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='contenido_reverso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='cuerpoTarjeta',
        ),
    ]
