# Generated by Django 4.0.3 on 2022-05-09 00:44

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nombre_tarjeta_tarjeta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='contenido',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='contenido_reverso',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
