# Generated by Django 4.0.3 on 2022-05-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tarjeta_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='tema',
            field=models.IntegerField(choices=[(None, 'None'), (1, 'Splendor'), (2, 'Retro'), (3, 'Air'), (4, 'Modest')], default=None, null=True),
        ),
    ]
