# Generated by Django 4.0.3 on 2022-05-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tarjeta_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='tema',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Splendor'), (2, 'Retro'), (3, 'Air'), (4, 'Modest')], default=0),
        ),
    ]
