# Generated by Django 4.0.3 on 2022-06-06 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_token_refresh_token_alter_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTarjeta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateTimeField(null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False)),
                ('contenido', markdownx.models.MarkdownxField()),
                ('contenido_reverso', markdownx.models.MarkdownxField(blank=True)),
                ('tema', models.IntegerField(choices=[(0, 'Default'), (1, 'Splendor'), (2, 'Retro'), (3, 'Air'), (4, 'Modest')], default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tarjeta',
                'verbose_name_plural': 'historical tarjetas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
