# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rembe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://rembe.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f5ffef2cc4c247efb02ec2807479d1f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ba8acd370b01427daf3ca3bdec6cd701 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: rembe.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f5ffef2cc4c247efb02ec2807479d1f7 }}/rembe:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rembe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9d6272e8f95a49fea13ce72cf48c2fe6 }}
        images: 'rembe.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f5ffef2cc4c247efb02ec2807479d1f7 }}/rembe:${{ github.sha }}'